baseurl = "http://xxi.iacmac.ru"
title = "XXI международный конгресс МАКМАХ"
canonifyurls = true
paginate = 6
theme = "aether"
publishDir = "docs"
languageCode = "ru-ru"
googleAnalytics = "UA-85066436-8"

[params]
brand = "XXI Конгресс МАКМАХ"
description = "XXI международный конгресс МАКМАХ по антимикробной терапии и клинической микробиологии"
bgcolor = "#387469"

homeimg = "img/grey-cloud.jpg"
thumbnail = "img/site_thumbnail.jpg"


[outputs]
  home = ["HTML", "JSON", "RSS"]  
  posts = ["HTML", "JSON", "RSS"]

[params.categories]
[[ params.categories.item ]]
    key = "Info"
    value = "Информация"
[[ params.categories.item ]]
    key = "may-22"
    value = "22 мая"
[[ params.categories.item ]]
    key = "may-23"
    value = "23 мая"
[[ params.categories.item ]]
    key = "may-24"
    value = "24 мая"
[[ params.categories.item ]]
    key = "Posters"
    value = "Постеры и тезисы"
